### ISSUE TITLE
BMP / pushColors bracket on wrong line

### ISSUE THREAD

**Issue by EforeZZ** [samuraijap/TFTLCD-Library#2]
Should be (note the commented line): 

void Adafruit_TFTLCD::pushColors(uint16_t *data, uint8_t len, boolean first) {
  uint16_t color;
  uint8_t  hi, lo;
  CS_ACTIVE;
  if(first == true) { // Issue GRAM write command only on first call
    CD_COMMAND;
    if(driver == ID_932X) write8(0x00);
    if ((driver == ID_9341) || (driver == ID_HX8357D) || (driver == ID_ILI9327)){
       write8(0x2C);
     } else if (driver == ID_S6D0154){
       write8(0x22);
     } else {
       write8(0x22);
  }}
  CD_DATA;
  while(len--) {
    color = *data++;
    hi    = color >> 8; // Don't simplify or merge these
    lo    = color;      // lines, there's macro shenanigans
    write8(hi);         // going on.
    write8(lo);
  }
  CS_IDLE;
//}
}

**Comment by samuraijap** [comment]
I modified the code.
